export const LAYER_ICON_SRC: Record<LayerType, any> = {
  AXE: require("../assets/layers/axe.png"),
  CRANE_TRUCK: require("../assets/layers/crane_truck.png"),
  ELECTRICAL_BOX: require("../assets/layers/electrical_box.png"),
  ELECTRICAL_POST: require("../assets/layers/electrical_post.png"),
  ELEVATOR: require("../assets/layers/elevator.png"),
  EXIT: require("../assets/layers/exit.png"),
  FAN_TRUCK: require("../assets/layers/fan_truck.png"),
  FIRE_EXTINGUISHER: require("../assets/layers/fire_extinguisher.png"),
  FIRST_AID: require("../assets/layers/first_aid.png"),
  GAS_CUTOFF: require("../assets/layers/gas_cutoff.png"),
  GAS_REDUCE: require("../assets/layers/gas_reduce.png"),
  GROUND_HYDRANT: require("../assets/layers/ground_hydrant.png"),
  HEAVY_TRUCK: require("../assets/layers/heavy_truck.png"),
  HOSE_REEL: require("../assets/layers/hose_reel.png"),
  LIGHT_TRUCK: require("../assets/layers/light_truck.png"),
  MSDS: require("../assets/layers/msds.png"),
  NOTE: require("../assets/layers/note.png"),
  PICTURE: require("../assets/layers/picture.png"),
  POWER_LINE: require("../assets/layers/power_line.png"),
  PUMP_CONNECTION: require("../assets/layers/pump_connection.png"),
  RISER: require("../assets/layers/riser.png"),
  SAFE_PUBLIC: require("../assets/layers/safe_public.png"),
  SUPPORT_TRUCK: require("../assets/layers/support_truck.png"),
  WALL_HYDRANT: require("../assets/layers/wall_hydrant.png"),
  WATER_CUTOFF: require("../assets/layers/water_cutoff.png"),
};

export const LAYER_FA: Record<LayerType, string> = {
  AXE: "ابزار شکستن",
  CRANE_TRUCK: "خودروی جرثقیل",
  ELECTRICAL_BOX: "جعبه تقسیم برق",
  ELECTRICAL_POST: "پست برق",
  ELEVATOR: "آسانسور",
  EXIT: "خروج اضطراری",
  FAN_TRUCK: "خودروی فن",
  FIRE_EXTINGUISHER: "کپسول",
  FIRST_AID: "کمک های اولیه",
  GAS_CUTOFF: "شیر قطع جریان گاز",
  GAS_REDUCE: "ایستگاه تقلیل فشار گاز",
  GROUND_HYDRANT: "هیدرانت زمینی",
  HEAVY_TRUCK: "خودروی سنگین",
  HOSE_REEL: "هوزریل",
  LIGHT_TRUCK: "خودروی سبک",
  MSDS: "محل ذخیره مواد خطرناک",
  NOTE: "یادداشت",
  PICTURE: "تصویر",
  POWER_LINE: "خط فشار قوی برق",
  PUMP_CONNECTION: "اتصال پمپ آتش نشانی",
  RISER: "رایزر",
  SAFE_PUBLIC: "محل تجمع امن",
  SUPPORT_TRUCK: "خودروی پشتیبان",
  WALL_HYDRANT: "هیدرانت دیواری",
  WATER_CUTOFF: "شیر قطع جریان آب",
};
